# 2. Data and Clear Data
In the previous notebook, "first analysis data," we examined the data as follows:  
1. Data type  
2. Data issues and problems  
3. Comparing data with each other  
4. Plotting charts from the data  
5. Assessing the data distribution to determine if it is normal or not  
6. Analyzing data behavior before movement, during movement, and after movement  
7. Identifying the type of movement and the dominant foot (which foot bears the most force and pulls the movement toward itself)  
8. Examining movement behavior

In [114]:
#basic
import os
import math

#analysis
import numpy as np
import pandas as pd

#Statistik
import scipy.stats as stats

#plot
import matplotlib.pyplot as plt
import seaborn as sns

one file for sampel

In [6]:
file_path = r"C:/Users/user/Desktop/Fatemeh/Analysis_Data/data/raw/Force data (novel loadsol 2)/Force data (novel loadsol 2)/loadsolASCII_25-11-11 09-38-11-074_Asphalt.txt"

with open(file_path, 'r', encoding='utf-8') as f:
    first_two_lines = [next(f) for _ in range(2)]

for i, line in enumerate(first_two_lines, 1):
    print(f"line {i}: {line.rstrip()}")

# name file
print(first_two_lines[0][5:].replace(".pdo\n",""))
# name Type of surface and last number
print(first_two_lines[1][8:].replace("\n","").split("_"))

line 1: File: loadsol_25-11-11 09-38-11-074.pdo
line 2: Comment:P02_Asphalt_01
 loadsol_25-11-11 09-38-11-074
['P02', 'Asphalt', '01']

In [152]:
file_path =  r"C:/Users/user/Desktop/Fatemeh/Analysis_Data/data/raw/Force data (novel loadsol 2)/Force data (novel loadsol 2)/loadsolASCII_25-11-11 09-38-11-074_Asphalt.txt"

def Rename_col(path):
    """find data in text
    Data = read file
    path = path of file
    line1 = 1st line name of file
    line2 = 2st line name of person and surface and one number
    line3 = 3rd line name of columns
    line4 = 4th line name of columns
    """
    #read data and line 1,2 ,3 4
    with open(file_path, "r", encoding="utf-8") as f:
        line1 = f.readline().rstrip("\n")
        line2 = f.readline().rstrip("\n")
        line3 = f.readline().rstrip("\n")
        line4 = f.readline().rstrip("\n")
    # line 1 and 2 and make name of columns
    a1 = np.array(line3.split("\t"))
    a2 = np.array(line4.split("\t"))[0:10]
    b = a1 + a2
    # replace name of columns
    name_colunms = np.char.replace(b, "Force[N]", "")
    name_colunms = np.char.replace(name_colunms, "::", "_")
    name_colunms = np.char.replace(name_colunms, "-", "_")
    #clear name of colums
    left_L =[]
    right_R = []
    for i in range(len(name_colunms)):
        left_L.append(name_colunms[i].rfind("_L"))
        right_R.append(name_colunms[i].rfind("_R"))
    for j in range(len(name_colunms)):
        if left_L[j] > 0:
            name_colunms[j] = name_colunms[j][left_L[j]+1:]
        elif right_R[j]>0:
            name_colunms[j] = name_colunms[j][right_R[j]+1:]
    name_colunms = np.char.replace(name_colunms, "L ", "L")
    # make name of dataframe
    name = line1[-7:-4]
    person_surface_number = line2[8:].split("_")
    main_name = (person_surface_number[1] + "_" +
                 person_surface_number[0]+ "_" +
                 person_surface_number[2]+ "_" +
                 name)
    #read row 5 to end of data
    df = pd.read_csv(file_path,
                     skiprows=4,
                     sep=r"\s+",
                     header=None)
    # rename columns of dataframe
    df.columns = s.tolist()
    df = df.rename(columns={"L":"Total_L_Foot", "R":"total_R_Foot"})
    Time = ef = np.arange(len(df)) * 0.01
    df = df.drop(columns="Time[secs]")
    df.insert(loc=0, column='Time', value=Time)



    
    return name, person_surface_number, name_colunms, main_name , df

q ,w,  s , z, x= Rename_col(file_path)
globals()[z] = x



# q ,w,  s , z, x= Rename_col(file_path)
# z

In [158]:
# C:\Users\user\Desktop\Fatemeh\Force data (novel loadsol 2)\Clear data xlsx


# read data form
input_path = r"C:/Users/user/Desktop/Fatemeh/Force data (novel loadsol 2)/Force data (novel loadsol 2)"
# save datafrom to folder as xlsx
output_path = r"C:/Users/user/Desktop/Fatemeh/Force data (novel loadsol 2)/Clear data xlsx"

os.makedirs(output_path, exist_ok=True)
file_names = [f for f in os.listdir(input_path) if f.endswith('.txt')]

file_names

['loadsolASCII_25-11-11 09-24-19-079.txt',
 'loadsolASCII_25-11-11 09-38-11-074.txt',
 'loadsolASCII_25-11-11 09-52-01-474.txt',
 'loadsolASCII_25-11-11 10-06-34-305.txt',
 'loadsolASCII_25-11-11 10-09-51-519.txt',
 'loadsolASCII_25-11-11 13-49-21-080.txt',
 'loadsolASCII_25-11-11 13-54-44-511.txt',
 'loadsolASCII_25-11-11 14-09-23-595.txt',
 'loadsolASCII_25-11-11 14-21-20-634.txt',
 'loadsolASCII_25-11-11 14-28-52-974.txt',
 'loadsolASCII_25-11-13 10-16-07-282.txt',
 'loadsolASCII_25-11-13 10-29-20-864.txt',
 'loadsolASCII_25-11-13 10-45-28-787.txt',
 'loadsolASCII_25-11-13 11-00-05-455.txt',
 'loadsolASCII_25-11-13 13-42-38-135.txt',
 'loadsolASCII_25-11-13 13-53-39-763.txt',
 'loadsolASCII_25-11-13 14-12-44-574.txt',
 'loadsolASCII_25-11-13 14-29-01-831.txt',
 'loadsolASCII_25-11-13 14-44-02-331.txt',
 'loadsolASCII_25-11-14 09-25-59-897.txt',
 'loadsolASCII_25-11-14 09-43-39-794.txt',
 'loadsolASCII_25-11-14 10-00-15-439.txt',
 'loadsolASCII_25-11-14 10-07-53-125.txt',
 'loadsolASCII_25-11-16 13-47-50-266.txt',
 'loadsolASCII_25-11-16 14-07-55-722.txt',
 'loadsolASCII_25-11-16 14-29-02-178.txt',
 'loadsolASCII_25-11-16 14-46-47-845.txt',
 'loadsolASCII_25-11-17 09-15-09-073.txt',
 'loadsolASCII_25-11-17 09-27-24-980.txt',
 'loadsolASCII_25-11-17 09-44-13-137.txt',
 'loadsolASCII_25-11-17 09-53-52-492.txt',
 'loadsolASCII_25-11-17 10-09-36-341.txt']

In [153]:
Asphalt_P02_01_074

,Time,L_Heel,L_Midfoot,L_Forefoot,Total_L_Foot,R_Forefoot,R_Midfoot,R_Heel,total_R_Foot
0,0.00,"182,040","162,060","127,280","471,380","84,680","99,760","145,000","329,440"
1,0.01,"182,040","162,060","127,280","471,380","84,680","99,760","142,100","326,540"
2,0.02,"185,000","164,280","127,280","476,560","87,000","99,760","142,100","328,860"
3,0.03,"182,040","162,060","127,280","471,380","87,000","99,760","139,780","326,540"
4,0.04,"182,040","164,280","127,280","473,600","87,000","99,760","137,460","324,220"
...,...,...,...,...,...,...,...,...,...
20755,207.55,"79,200","169,290","236,610","485,100","177,000","94,500","32,250","303,750"
20756,207.56,"77,220","172,260","236,610","486,090","180,000","94,500","30,000","304,500"
20757,207.57,"74,250","169,290","241,560","485,100","182,250","92,250","27,000","301,500"
20758,207.58,"72,270","167,310","241,560","481,140","184,500","90,000","27,000","301,500"
20759,207.59,"72,270","167,310","247,500","487,080","187,500","87,000","24,750","299,250"

In [ ]:
074_Asphalt_P02_01

In [126]:
path = r"C:/Users/user/Desktop/Fatemeh/Force data (novel loadsol 2)/Force data (novel loadsol 2)"

In [93]:
file_path =  r"C:/Users/user/Desktop/Fatemeh/Analysis_Data/data/raw/Force data (novel loadsol 2)/Force data (novel loadsol 2)/loadsolASCII_25-11-11 09-38-11-074_Asphalt.txt"

# خواندن از سطر 5 به بعد
df = pd.read_csv(file_path, 
                 skiprows=4,      # رد کردن سطرهای 1 تا 4
                 sep=r"\s+",      # جداکننده: هر تعداد فاصله/تب
                 header=None)     # چون header در سطرهای اول بود
li = s.tolist()
df.columns = li
df.rename(columns={"L":"Total_L", "R":"total_R"})

,Time[secs],L_Heel,L_Midfoot,L_Forefoot,Total_L,Time[secs],R_Forefoot,R_Midfoot,R_Heel,total_R
0,"0,000","182,040","162,060","127,280","471,380","0,000","84,680","99,760","145,000","329,440"
1,"0,010","182,040","162,060","127,280","471,380","0,010","84,680","99,760","142,100","326,540"
2,"0,020","185,000","164,280","127,280","476,560","0,020","87,000","99,760","142,100","328,860"
3,"0,030","182,040","162,060","127,280","471,380","0,030","87,000","99,760","139,780","326,540"
4,"0,040","182,040","164,280","127,280","473,600","0,040","87,000","99,760","137,460","324,220"
...,...,...,...,...,...,...,...,...,...,...
20755,"207,550","79,200","169,290","236,610","485,100","207,550","177,000","94,500","32,250","303,750"
20756,"207,560","77,220","172,260","236,610","486,090","207,560","180,000","94,500","30,000","304,500"
20757,"207,570","74,250","169,290","241,560","485,100","207,570","182,250","92,250","27,000","301,500"
20758,"207,580","72,270","167,310","241,560","481,140","207,580","184,500","90,000","27,000","301,500"
20759,"207,590","72,270","167,310","247,500","487,080","207,590","187,500","87,000","24,750","299,250"

In [ ]:
file_path =  r"C:/Users/user/Desktop/Fatemeh/Analysis_Data/data/raw/Force data (novel loadsol 2)/Force data (novel loadsol 2)/loadsolASCII_25-11-11 09-38-11-074_Asphalt.txt"


# خواندن 4 سطر اول (نگه می‌داریم برای استخراج نام ستون‌ها)
# with open(file_path, "r", encoding="utf-8") as f:
#     line1 = f.readline().rstrip("\n")
#     line2 = f.readline().rstrip("\n")
#     line3 = f.readline().rstrip("\n")
#     line4 = f.readline().rstrip("\n")
# print(line1)
# print(line2)
# print(line3)
# print(line4)

def Rename_col(Data, path):
    """find data in text
    Data = read file
    path = path of file
    line1 = 1st line name of file
    line2 = 2st line name of person and surface and one number
    line3 = 3rd line name of columns
    line4 = 4th line name of columns
    """
    with open(path, "r", encoding="utf-8") as f:
        line2 = f.readline().rstrip("\n")
        line2 = f.readline().rstrip("\n")
        line3 = f.readline().rstrip("\n")
        line4 = f.readline().rstrip("\n")
    a1 = np.array(line3.split("\t"))
    a2 = np.array(line4.split("\t"))[0:10]
    b = a1 + a2
    name_colunms = np.char.replace(b, "Force[N]", "")
    name_colunms = np.char.replace(name_colunms, "::", "_")
    name_colunms = np.char.replace(name_colunms, "-", "_")
    left_L =[]
    right_R = []
    for i in range(len(name_colunms)):
        left_L.append(name_colunms[i].rfind("_L"))
        right_R.append(name_colunms[i].rfind("_R"))

    for j in range(len(name_colunms)):
        if left_L[j] > 0:
            name_colunms[j] = name_colunms[j][left_L[j]+1:]
        elif right_R[j]>0:
            name_colunms[j] = name_colunms[j][right_R[j]+1:]
    name_colunms = np.char.replace(name_colunms, "L ", "L")
    return name_colunms


Rename_col(file_path)

TypeError: Rename_col() missing 1 required positional argument: 'path'

In [ ]:
name_colunms

array(['Time[secs]', 'L_Heel', 'L_Midfoot', 'L_Forefoot', 'L',
       'Time[secs]', 'R_Forefoot', 'R_Midfoot', 'R_Heel', 'R'],
      dtype='<U10')

In [ ]:
line1[-7:-4]

array(['Time[secs]', 'L_Heel', 'L_Midfoot', 'L_Forefoot', 'L',
       'Time[secs]', 'R_Forefoot', 'R_Midfoot', 'R_Heel', 'R'],
      dtype='<U10')